### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [collective/collective.complexrecordsproxy#1]
Would it be possible to make a new release of this package ? or give me the right to do it myself on Pypi (user: laz) ?

Thanks a lot !

**Comment by laulaz** [comment]
@tomgross can you help me with this ?  🙏

**Comment by tomgross** [comment]
I released 1.1 https://pypi.org/project/collective.complexrecordsproxy/1.1/
What is your name on pypi? I can add you as maintainer.

**Comment by laulaz** [comment]
Thank you @tomgross 
> user: laz

:blush:

**Comment by tomgross** [comment]
I sent you an invite on pypi.
